name: personal_finance
description: "A new Flutter project."

version: 1.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.37

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  equatable: ^2.0.5
  flutter_bloc: ^9.0.0
  firebase_auth: ^5.5.2
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^7.1.0
  firebase_core: ^3.13.0
  connectivity_plus: ^5.0.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.0.0
  image_picker: ^1.1.1
  flutter_svg: ^2.2.1
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:  
  uses-material-design: true

  assets:
    - .env
    - assets/logo.png
    - assets/images/
    - assets/icons/
    - assets/privacy_policy.md

# Launcher icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  adaptive_icon_foreground: assets/logo.png
  adaptive_icon_background: "#0E8F5B"
  min_sdk_android: 21
